### ISSUE TITLE
Recommendations for header

### ISSUE THREAD

**Issue by wendywarren** [lexyfh/web-design-2-independent-project#1]
Hi @lexyfh,

I just took a look at your header and it looks like the markup wasn't exactly as I had done it for the hamburger menu example. You had the logo and checkbox initially in the `<nav>` and forgot to include the `<span>` within the label to draw the three lines.

```
<header role="banner">
  <span class="logo"><img src="images/conspiracy-logo.svg" alt="Conspiracies in Media logo"></span>
  <input type="checkbox" id="nav-toggle" class="nav-toggle">
  <nav id="nav" role="navigation">            
    <ul>
      <li><a href="index.html">Home</a></li>
      <li><a href="celebrity-imposters.html">Celebrity Imposters</a></li>
      <li><a href="avril-lavigne.html">Avril Lavigne</a></li>
    </ul>
  </nav>
  <label for="nav-toggle" class="nav-toggle-label">
    <span></span>
  </label>
</header>
```

I don't believe at this point there is anything to change in the css unless you would like the nav bar to just stay at the top of the page so it's not visible when you scroll down or if you want it to be fixed and always remain visible.

```
header {
  background: #d3d4d9;
  text-align: center;
  /* position: fixed;
  z-index: 999; */
  position: relative;
  width: 100%;
}
```

Regardless, you have to include a position. Either fixed or relative. Play around with both and see what you think works best.

I'll take a look at your layout shortly.

Thanks,
Wendy

**Comment by lexyfh** [comment]
Okay, I added the span tag but am I supposed to put anything in it?

**Comment by wendywarren** [comment]
@lexyfh 

No, you leave it empty and the content gets placed in it through the css (the three white lines).
