### ISSUE TITLE
Hero banner

### ISSUE THREAD

**Issue by wendywarren** [lexyfh/web-design-2-independent-project#2]
Hi @lexyfh,

Doing something as simple as this to your `.hero-banner` will place the text and image within the same grid column and row. The align-self property is what brings the text to the bottom. 

```
.hero-banner {
  display: grid;
  grid-template-columns: 1fr;
}

.hero-banner img {
  grid-column: 1/-1;
  grid-row: 1;
}

.hero-banner h1 {
  grid-column: 1/-1;
  grid-row: 1;
  align-self: end;
}
```

You will have to adjust the margin for the text and the font-size from mobile to desktop within your media query.

It might be worth considering cropping the image to not be as high or set a wrapper around all content so that none of your content expands more than 2000px and you have extra space on either side. 

Wendy

**Comment by lexyfh** [comment]
Awesome, cropped the image, not sure how to do the wrapper?

**Comment by wendywarren** [comment]
@lexyfh  - We can tackle the wrapper at 1:30 today. Does that time still work for you?
